# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HoZxMKGw0SsfbHAOStFhGQCyN5s8czLC
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs

# 1. Generate synthetic data
X, y_true = make_blobs(n_samples=300, centers=4, cluster_std=0.60, random_state=42)

# 2. K-Means algorithm from scratch
def initialize_centroids(X, k):
    idx = np.random.choice(X.shape[0], k, replace=False)
    return X[idx]

def assign_clusters(X, centroids):
    dists = np.linalg.norm(X[:, np.newaxis] - centroids, axis=2)
    return np.argmin(dists, axis=1)

def update_centroids(X, labels, k):
    return np.array([X[labels == i].mean(axis=0) for i in range(k)])

def kmeans(X, k, max_iters=100):
    centroids = initialize_centroids(X, k)
    for _ in range(max_iters):
        labels = assign_clusters(X, centroids)
        new_centroids = update_centroids(X, labels, k)
        if np.allclose(centroids, new_centroids):
            break
        centroids = new_centroids
    return labels, centroids

# 3. Run algorithm and visualize
labels, centroids = kmeans(X, 4)

plt.scatter(X[:, 0], X[:, 1], c=labels, cmap="viridis")
plt.scatter(centroids[:, 0], centroids[:, 1], c='red', s=300, marker='x')
plt.title("K-Means Clustering (from scratch)")
plt.savefig("clusters.png")
plt.show()

# 4. Calculate Inertia
inertia = np.sum((X - centroids[labels]) ** 2)
print("Custom K-Means Inertia:", inertia)

plt.savefig("filename.png")